output_dir: ''
root_path: ''
pretrain_clip_path: ''
NUM_FRAMES: 16
MODEL_ARCH: 'ViT-B/16'
pool: 'mean'
learning_rate: 1e-4
train_batch_size: 2
#30000 is necessary
max_train_steps: 90000
checkpointing_steps: 5000
validation_steps: 30000

seed: 123
mixed_precision: fp16
use_8bit_adam: False
gradient_checkpointing: True
enable_xformers_memory_efficient_attention: True
